version: 2.1

executors:
  base:
    docker:
      - image: cimg/base:2020.10

jobs:
  docker_build:
    parameters:
      cypress_version:
        type: string
      cimg_node_version:
        type: string
    executor: base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
              docker build \
                -t sprygroup/cimg-node:<< parameters.cimg_node_version >>-<< parameters.cypress_version >> \
                --build-arg VCS_REF=${CIRCLE_SHA1} \
                --build-arg BUILD_DATE=`date --rfc-3339=seconds | sed 's/ /T/'` \
                --build-arg CIMG_NODE_VERSION=<< parameters.cimg_node_version >> \
                --build-arg CYPRESS_VERSION=<< parameters.cypress_version >> \
                .
      - run: docker login --username "${DOCKER_USER}" --password "${DOCKER_PASS}"
      - run: docker push sprygroup/cimg-node:<< parameters.cimg_node_version >>-<< parameters.cypress_version >>

workflows:
  commit:
    jobs:
      - docker_build:
          context:
            - spryci
          matrix:
            parameters:
              cypress_version: ["5.1.0", "5.2.0", "5.3.0", "5.4.0", "5.5.0"]
              cimg_node_version: ["14.14", "14.15", "15.0"]

